# Documentation available at http://expeditor-docs.es.chef.io/

product_key: supermarket

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: supermarket-notify

automate:
  organization: products
  project: supermarket

github:
  # The file where our CHANGELOG is kept. This file is updated automatically with
  # details from the Pull Request via the `built_in:update_changelog` merge_action.
  changelog_file: "CHANGELOG.md"
  # clean up PR branches when they've merged
  delete_branch_on_merge: true
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # The file where the MAJOR.MINOR.PATCH version is kept. The version in this file
  # is bumped automatically via the `built_in:bump_version` merge_action.
  version_file: "VERSION"

changelog:
  categories:
    - "Aspect: Correctness": "Bug Fixes"
    - "Aspect: Security": "Security Fixes"
    - "Bug": "Bug Fixes"
    - "Enhancement": "Enhancements"
    - "Feature": "Enhancements"
    - "Type: Breaking Change": "Breaking Changes"
    - "Type: Bug": "Bug Fixes"
    - "Type: Chore": "Maintenance Updates"
    - "Type: Deprecation": "Deprecations"
    - "Type: Enhancement": "Enhancements"
    - "Type: Regression": "Bug Fixes"
    - "Type: Tech Debt": "Maintenance Updates"

pipelines:
  - verify
  - omnibus/release
  - omnibus/adhoc:
      definition: .expeditor/release.omnibus.yml
      env:
        - ADHOC: true

# These actions are taken, in order they are specified, anytime a Pull Request is merged.
merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
  - trigger_pipeline:omnibus/release:
      ignore_labels:
        - "Expeditor: Skip Omnibus"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
      only_if: built_in:bump_version

# These actions are taken, in the order specified, when an Omnibus artifact is promoted
# within Chef's internal artifact storage system.
#
# TODO: add promoted_to_unstable action to update changelog with modified omnibus components
subscriptions:
  - workload: artifact_published:current:supermarket:*
    actions:
      - built_in:update_acc
  - workload: artifact_published:stable:supermarket:*
    actions:
      - built_in:rollover_changelog
      - built_in:notify_chefio_slack_channels

promote:
  actions:
    - built_in:promote_artifactory_artifact
  channels:
    - unstable
    - current
    - stable
