require:
  - chefstyle
  - rubocop-rails
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/**/*
    - engines/**/*
    - vendor/**/*
    - node_modules/**/*
Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned
Lint/UselessAssignment:
  Exclude:
    - config.rb
Rails/SkipsModelValidations:
  Whitelist:
    - increment_counter
    - touch
Style/SymbolArray:
  EnforcedStyle: brackets
