version: '2'
services:
  db:
    image: postgres:9.3
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${USER}
  redis:
    image: redis:3.0
    ports:
      - "127.0.0.1:6379:6379"
  supermarket-rspec:
    command: /workdir/src/supermarket/scripts/bk_supermarket.sh
    image: chefes/a1-buildkite:latest
    expose:
      - "5432"
      - "6379"
    volumes:
      - ../../:/workdir
    working_dir: /workdir/src/supermarket
    links:
      - redis:redis-server
